# Site settings
title: Python-Sprints
email: pandanistas@numfocus.org
description: > # this means to ignore newlines until "baseurl:"
  pandanistas is a community to promote diversity in pandas and open source contributors
baseurl: "/pandanistas_prg/" # the subpath of your site, e.g. /blog/
url: "https://pandanistas.org/pandanistas_org" # the base hostname & protocol for your site
twitter_username: pandanistas
github_username:  pandanistas

# Build settings
include: ['_pages']
sass:
  sass_dir: _sass
kramdown:
  input: GFM
include: ["_test.html", "_static", "pandas/guide/_static", "_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - static/images/sources/
  - _pages/02_get_started.html
  - DOCS/
future: true
timezone: Europe/London

collections:
  sponsors:
    output: false
  chapters:
    output: true
  projects:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      is_chapter: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# command to run build locally:
# bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml
